application: devhaggle
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /assets/css
  static_dir: assets/css
  secure: always

- url: /assets/js
  static_dir: assets/js
  secure: always

- url: /assets/img
  static_dir: assets/img
  secure: always

- url: /assets/fonts
  static_dir: assets/fonts
  secure: always

#- url: /endpoints
#  static_dir: handlers/endpoints 
#  secure: always

- url: /fetch_token
  script: handlers.endpoints.app
  secure: always

- url: /callback
  script: handlers.endpoints.app
  secure: always

- url: /endpoints.*
  script: handlers.endpoints.app
  secure: always

- url: /api/.*
  script: handlers.api.app
  secure: always

- url: /.*
  script: handlers.index.app
  secure: always

libraries:
- name: django
  version: "1.4"
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
